name: advent-of-code2019
version: 0.1.0.0
author: Myron Wu
maintainer: Myron Wu <myronwu@gmail.com>

dependencies:
  - base
  - async
  - containers
  - monad-loops
  - relude
  - split
  - text
  - vector

default-extensions:
  - GeneralizedNewtypeDeriving
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables

ghc-options:
  - -Wall

executables:
  day-1:
    main: day-1.hs
    source-dirs: src
  day-2:
    main: day-2.hs
    source-dirs: src
  day-3:
    main: day-3.hs
    source-dirs: src
  day-4:
    main: day-4.hs
    source-dirs: src
  day-5:
    main: day-5.hs
    source-dirs: src
  day-6:
    main: day-6.hs
    source-dirs: src
    dependencies: [ fgl ]
  day-7:
    main: day-7.hs
    source-dirs: src
  day-8:
    main: day-8.hs
    source-dirs: src
  day-9:
    main: day-9.hs
    source-dirs: src
