name: advent-of-code2019
version: 0.1.0.0
author: Myron Wu
maintainer: Myron Wu <myronwu@gmail.com>

dependencies:
  - base
  - containers
  - monad-loops
  - relude
  - text
  - vector

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables

ghc-options:
  - -Wall

executables:
  day-1:
    main: day-1.hs
    source-dirs: src
  day-2:
    main: day-2.hs
    source-dirs: src
  day-3:
    main: day-3.hs
    source-dirs: src
  day-4:
    main: day-4.hs
    source-dirs: src
  day-5:
    main: day-5.hs
    source-dirs: src
